server:
  port: 8081

spring:
  profiles:
    #主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
    active: dev
  jackson:
    #时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
    #时区设置
    time-zone: Asia/Chongqing
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/simple
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/user/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.study.user.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false

#logging
logging:
  config: classpath:logback-config.xml

security:
  user:
    name: user
    password: pwd


